version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: wellness-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: wellness_events
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - wellness-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wellness-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/wellness_events?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      PORT: 5000
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - wellness-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wellness-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - wellness-network

volumes:
  mongodb_data:

networks:
  wellness-network:
    driver: bridge